### ISSUE TITLE
语音识别延迟

### ISSUE THREAD

**Issue by yuanziyu** [Lin-Jiaxiang/audioAPohot#1]
您好，我复现完您的代码后，发现语音识别速度并没有您在文章中展示的动图快。延迟比较严重的时候接近10s，最快的时候也需要5秒左右，您能告诉我该如何解决吗？而且我也试过使用微信同声传译和腾讯智能云语音插件，他们都有延迟的现象。

**Comment by Lin-Jiaxiang** [comment]
是使用真机调式吗，
在pc上使用微信开发者工具调式时延迟比较高，我当时是手机录屏，然后转gif的

**Comment by yuanziyu** [comment]
是的，我用的是真机调试。开始录音后后台显示在等待同步api调用会耗时较久，而且在我朋友的电脑和手机上调试也是一样有比较长的延迟。您觉得应该是哪方面的原因呢？

**Comment by yuanziyu** [comment]
感谢您的回复。 我用的是手机调试，没有用pc端的真机调试。后台显示在语音获取到之后会在等待API 同步时花的时间比较久一点。等个几秒，相应的文本才会返回过来。而且在我的同事的电脑和手机上测试也是有延迟。您觉得应该是哪方面的原因呢？感谢赐教------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月7日(星期一) 下午4:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Lin-Jiaxiang/audioAPohot] 语音识别延迟 (#1)

**Comment by Lin-Jiaxiang** [comment]
我晚上回去跑一下看看  不知道是不是因为百度这个api免费版延迟高了

**Comment by Lin-Jiaxiang** [comment]
我晚上回去跑一下看看  不知道是不是因为百度这个api免费版延迟高了

**Comment by yuanziyu** [comment]
好的好的，谢谢您

**Comment by Lin-Jiaxiang** [comment]
用小程序体验版进入会快很多，应该是开发者工具的延迟

**Comment by yuanziyu** [comment]
好的，明天我再试一下，麻烦您了。感谢🤝------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月7日(星期一) 晚上9:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Lin-Jiaxiang/audioAPohot] 语音识别延迟 (#1)
